---
# tasks file for odoo_role
- name: Create a project directory
  ansible.builtin.file:
    path: /tmp/odoo
    state: directory
    mode: '0755'

- name: Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /tmp/odoo/docker-compose.yml

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: /tmp/odoo
    recreate: "always"
  register: output
  ignore_errors: true
- debug:
    var: output

- name: Remove compose file
  ansible.builtin.file:
    path: /tmp/odoo/docker-compose.yml
    state: absent

- name: Deployment failure
  ansible.builtin.fail:
    msg: "Services deployment failed."
  when: output.failed != false
